name: Captura tráfico Azteca

on:
  schedule:
    - cron: '0  19 * * *'   # 13:00 CDMX
    - cron: '15 19 * * *'   # 13:15 CDMX
    - cron: '30 19 * * *'   # 13:30 CDMX
    - cron: '45 19 * * *'   # 13:45 CDMX
    - cron: '0  20 * * *'   # 14:00 CDMX
    - cron: '15 20 * * *'   # 14:15 CDMX
    - cron: '30 20 * * *'   # 14:30 CDMX
    - cron: '45 20 * * *'   # 14:45 CDMX
    - cron: '0  21 * * *'   # 15:00 CDMX
    - cron: '15 21 * * *'   # 15:15 CDMX
    - cron: '30 21 * * *'   # 15:30 CDMX
    - cron: '45 21 * * *'   # 15:45 CDMX
    - cron: '0  22 * * *'   # 16:00 CDMX
    - cron: '15 22 * * *'   # 16:15 CDMX
    - cron: '30 22 * * *'   # 16:30 CDMX
    - cron: '45 22 * * *'   # 16:45 CDMX
    - cron: '0  23 * * *'   # 17:00 CDMX
    - cron: '15 23 * * *'   # 17:15 CDMX
    - cron: '30 23 * * *'   # 17:30 CDMX
    - cron: '45 23 * * *'   # 17:45 CDMX
    - cron: '0  0  * * *'   # 18:00 CDMX
    - cron: '15 0  * * *'   # 18:15 CDMX
    - cron: '30 0  * * *'   # 18:30 CDMX
    - cron: '45 0  * * *'   # 18:45 CDMX
    - cron: '0  1  * * *'   # 19:00 CDMX
    - cron: '15 1  * * *'   # 19:15 CDMX
    - cron: '30 1  * * *'   # 19:30 CDMX
    - cron: '45 1  * * *'   # 19:45 CDMX
    - cron: '0  2  * * *'   # 20:00 CDMX
    - cron: '15 2  * * *'   # 20:15 CDMX
    - cron: '30 2  * * *'   # 20:30 CDMX
    - cron: '45 2  * * *'   # 20:45 CDMX
    - cron: '0  3  * * *'   # 21:00 CDMX
    - cron: '15 3  * * *'   # 21:15 CDMX
    - cron: '30 3  * * *'   # 21:30 CDMX
    - cron: '45 3  * * *'   # 21:45 CDMX
    - cron: '0  4  * * *'   # 22:00 CDMX
    - cron: '15 4  * * *'   # 22:15 CDMX
    - cron: '30 4  * * *'   # 22:30 CDMX
    - cron: '45 4  * * *'   # 22:45 CDMX
    - cron: '0  5  * * *'   # 23:00 CDMX
    - cron: '15 5  * * *'   # 23:15 CDMX
    - cron: '30 5  * * *'   # 23:30 CDMX
    - cron: '45 5  * * *'   # 23:45 CDMX
  workflow_dispatch:

jobs:
  captura:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # <-- agrega esta línea
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar captura
        env:
          ROUTES_API_KEY: ${{ secrets.ROUTES_API_KEY }}
        run: python captura_trafico.py

      - name: Commit y push de datos
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/trafico_azteca.csv
          git diff --staged --quiet || git commit -m "datos: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
